# ASP.NET Core
- task: AzureAppConfigurationPush@1
  inputs:
    azureSubscription: 'Leap-Dev-Vendor shared sub(1)(27ecc5df-75fd-470a-8215-794d8e807911)'
    ConfigstoreName: 'TestAppConfigAspTutorial'
    ConfigurationFile: 'Anne56njeri/FirstPipeLine / azure-pipelines.yml'
    Separator: '/'
    Strict: false
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
    
    windows:
      imageName: "vs2017-win2016"
  maxParallel: 2

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
